[project]
name = "bionerf"
version = "1.0"

dependencies = ["nerfstudio"] 

[tool.setuptools.packages.find]
include = ["bionerf*"]

[project.entry-points.'nerfstudio.method_configs']
bionerf = 'bionerf.bionerf_config:bionerf_method'
